# Generated by Django 5.1.2 on 2025-02-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_encryptedimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedimage',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
