# Generated by Django 5.1.2 on 2025-02-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_encryptedimage_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Key',
        ),
    ]
