# Generated by Django 5.1.2 on 2025-02-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedimage',
            name='original_image',
        ),
    ]
