# Generated by Django 5.1.2 on 2025-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_encryptedimage_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedimage',
            name='key_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedimage',
            name='shuffle_indices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
