# Generated by Django 5.1.2 on 2025-04-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_encryptedimage_key_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='original_images/'),
        ),
    ]
