# Generated by Django 5.1.2 on 2025-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_encryptedimage_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedimage',
            name='original_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
