# Generated by Django 5.1.2 on 2025-04-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_encryptedimage_original_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=50)),
                ('result_value', models.FloatField()),
                ('attacked_on', models.DateTimeField(auto_now_add=True)),
                ('modified_key_used', models.CharField(blank=True, max_length=255, null=True)),
                ('pixel_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('original_pixel', models.IntegerField(blank=True, null=True)),
                ('modified_pixel', models.IntegerField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.encryptedimage')),
            ],
        ),
    ]
