# Generated by Django 5.1.2 on 2025-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedimage',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='encryptedimage',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
