# Generated by Django 5.1.2 on 2025-04-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_encryptedimage_otp_code_encryptedimage_otp_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
